SDL_HEADER_DIR=C:/SDL2/SDL2-2.0.3/i686-w64-mingw32/include/SDL2/
SDL_HEADER_DIR_IMAGE=C:/SDL2/SDL2_image-2.0.0/i686-w64-mingw32/include/SDL2/
SDL_HEADER_DIR_TTF=C:/SDL2/SDL2_ttf-2.0.12/i686-w64-mingw32/include/SDL2/
SDL_HEADER_DIR_MIXER=C:/SDL2/SDL2_mixer-2.0.0/i686-w64-mingw32/include/SDL2/

SDL_LINKER_DIR=C:/SDL2/SDL2-2.0.3/i686-w64-mingw32/lib/
SDL_LINKER_DIR_IMAGE=C:/SDL2/SDL2_image-2.0.0/i686-w64-mingw32/lib/
SDL_LINKER_DIR_TTF=C:/SDL2/SDL2_ttf-2.0.12/i686-w64-mingw32/lib/
SDL_LINKER_DIR_MIXER=C:/SDL2/SDL2_mixer-2.0.0/i686-w64-mingw32/lib/

SDL_LINKER_OPTIONS=-lmingw32 -lSDL2main -lSDL2
SDL_LINKER_OPTIONS_IMAGE=-lSDL2_image
SDL_LINKER_OPTIONS_TTF=-lSDL2_ttf
SDL_LINKER_OPTIONS_MIXER=-lSDL2_mixer

SDL_OPTIONS=-I$(SDL_HEADER_DIR) -L$(SDL_LINKER_DIR) $(SDL_LINKER_OPTIONS)
SDL_OPTIONS_IMAGE=-I$(SDL_HEADER_DIR_IMAGE) -L$(SDL_LINKER_DIR_IMAGE) $(SDL_LINKER_OPTIONS_IMAGE)
SDL_OPTIONS_TTF=-I$(SDL_HEADER_DIR_TTF) -L$(SDL_LINKER_DIR_TTF) $(SDL_LINKER_OPTIONS_TTF)
SDL_OPTIONS_MIXER=-I$(SDL_HEADER_DIR_MIXER) -L$(SDL_LINKER_DIR_MIXER) $(SDL_LINKER_OPTIONS_MIXER)

CFLAGS=-Wall -g -std=c11
CC=gcc


#NOTE!!!!! - The order is important. The .c files must come before the linker flags
#http://stackoverflow.com/questions/11893996/why-does-the-order-of-l-option-in-gcc-matter

#Hello SDL
game: main.c
	$(CC) $+ $(CFLAGS) $(SDL_OPTIONS) $(SDL_OPTIONS_IMAGE) -o bin/$@

